version: "3.8"

services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./tgrt_full_stack_technical_task.db
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./server/static:/app/static
      - ./server/tgrt_full_stack_technical_task.db:/app/tgrt_full_stack_technical_task.db
    depends_on:
      - redis
    # restart: unless-stopped

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
    # restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    # restart: unless-stopped

  celery:
    build: ./server
    command: celery -A app.services.task_queue worker --loglevel=info
    environment:
      - DATABASE_URL=sqlite:///./tgrt_full_stack_technical_task.db
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./client/public:/app/static
    depends_on:
      - redis
      - server
    # restart: unless-stopped
